### ISSUE TITLE
Add a note or something somewhere that clarifies that a "QuickLook" folder must be CREATED

### ISSUE THREAD

**Issue by Scyth3934** [Timac/QLCARFiles#3]
I got confused with the instruction "Move QLCARFiles.qlgenerator to ~/Library/QuickLook/QLCARFiles.qlgenerator".

Considering there was not an existing folder called "QuickLook" at ~/Library, I checked /Library instead and saw that there was a "QuickLook" folder there. I didn't know how you expected anyone to be able to move a file there without temporarily disabling SIP. Just to make sure, I added a "QuickLook" folder to ~/Library and put the binary inside (which worked).
I suggest you add a note or something somewhere that clarifies that a "QuickLook" folder must be created in ~/Library, even though there is an existing folder in /Library that seems like it _should_ be the correct one.

**Comment by Timac** [comment]
Thanks a lot for the feedback. I added the missing installation instructions in the README and the note about creating the `~/Library/QuickLook/` folder.

I also added this note on the original blog article at https://blog.timac.org/2018/1112-quicklook-plugin-to-visualize-car-files/
